#!/bin/bash

logfile=$(ls -rt .snakemake/log/*.log |tail -n1)
echo "Lastest log file is:"
ls -l $logfile
echo "##### Looking for workflow execution errors..."
fgrep "Error executing" $logfile
echo "##### Done looking for workflow execution errors."
echo "##### Looking for DRMAA errors..."
fgrep "DRMAA Error" $logfile 
echo "##### Done looking for DRMAA errors."

